### ISSUE TITLE
ImportError: DLL load failed while importing clarabel: The specified procedure could not be found.

### ISSUE THREAD

**Issue by jiveshkalra** [oxfordcontrol/Clarabel.rs#128]
I am using Python 3.8 on a conda venv  , I installed clarabel using pip and I am facing errors in importing clarabel
```
Python 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32 
>>> from clarabel import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\envs\<env>\lib\site-packages\clarabel\__init__.py", line 1, in <module>
    from .clarabel import *
ImportError: DLL load failed while importing clarabel: The specified procedure could not be found.
```

**Comment by jiveshkalra** [comment]
```
pip install clarabel==0.5
```
 worked for me
